// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTw-YfvM0JY3InTccauB-0xyZDho9Svw',
    appId: '1:190263180077:web:d8d068fdf64adc22c871a4',
    messagingSenderId: '190263180077',
    projectId: 'instagram-clone-5f512',
    authDomain: 'instagram-clone-5f512.firebaseapp.com',
    storageBucket: 'instagram-clone-5f512.appspot.com',
    measurementId: 'G-6J1TD5NN39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-V4cAgVpebLCkmo_DsRIFCynFOpIdg94',
    appId: '1:190263180077:android:5290d59bc6b13c6dc871a4',
    messagingSenderId: '190263180077',
    projectId: 'instagram-clone-5f512',
    storageBucket: 'instagram-clone-5f512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGw2Yw8NWSM0_C_bAwZCJEi25GOgndvvc',
    appId: '1:190263180077:ios:cd84892b0134a18bc871a4',
    messagingSenderId: '190263180077',
    projectId: 'instagram-clone-5f512',
    storageBucket: 'instagram-clone-5f512.appspot.com',
    iosClientId: '190263180077-dnrplfgs97vtb99do4tj13ne6fn9k0ac.apps.googleusercontent.com',
    iosBundleId: 'com.vishnukp.instagramClone',
  );
}
